services:
  mysql_db:
    image: mysql:8.0
    container_name: my_diploma_db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  node_app:
    build: .
    container_name: my_diploma_app
    # ports:   # закомментировано, так как порт пробрасывает Nginx
    #   - "3000:3000"
    depends_on:
      mysql_db:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_PORT: ${DB_PORT}
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      SESSION_SECRET: ${SESSION_SECRET}
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: my_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - node_app
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my_phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: ${PMA_HOST:-mysql_db}
      PMA_PORT: ${PMA_PORT:-3306}
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 300M
    depends_on:
      - mysql_db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data: