name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: my_diploma_test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: 20

      - run: npm ci

      - name: Init DB
        run: |
          mysql -h 127.0.0.1 -u root -proot -e "SHOW DATABASES;"
          mysql -h 127.0.0.1 -u root -proot my_diploma_test_db < db/init.sql
          mysql -h 127.0.0.1 -u root -proot my_diploma_test_db -e "SHOW TABLES;"

      - name: Test
        run: npm test
        env:
          NODE_ENV: test
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASSWORD: root
          DB_DATABASE: my_diploma_test_db
          RATE_LIMIT_MAX: 5